### ISSUE TITLE
QUIC is orphaned

### ISSUE THREAD

**Issue by antshi** [mlkrock/BasisGraphicalLasso#1]
dependency QUIC is not available on CRAN anymore:

https://cran.r-project.org/web/packages/QUIC/index.html

would BigQUIC do the work?

**Comment by mlkrock** [comment]
Hi Antoniya, 
Thanks for the comment and sorry for the really late response here. Your fix with glasso definitely works, but will be slower than QUIC. BigQUIC takes the rectangular data matrix as input instead of sample covariance, which is annoying for this algorithm.

It looks like the QUIC package got removed because it's not maintained anymore. I would still personally recommend it, I think this can work: 

library(devtools) 
install_github("cran/QUIC")
